apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
   - port: 27017
     targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mongo
spec:
  podSelector:
    matchLabels:
      app: mongo
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: hell-js-vulnerable-backend
