apiVersion: v1
kind: Service
metadata:
  name: hell-js-secure-backend
spec:
  ports:
   - port: 27332
     targetPort: 8080
  selector:
    app: hell-js-secure-backend
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: hell-js-secure-backend
spec:
  podSelector:
    matchLabels:
      app: hell-js-secure-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8080
    from: []
